[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.8.3", features = ["multipart"] }
dotenvy = "0.15.7"
serde = { "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serve = "0.0.1"
tokio = { version = "1.44.2", features = ["full"] }
tower-http = { version = "0.6.2", features = ["cors", "fs"] }
